### ISSUE TITLE
Admin Access

### ISSUE THREAD

**Issue by JMace88** [2401-Group-A/Capstone-EComSite#13]
- [x] View list of all products
- [x] View list of all users. Should be able to see all user info except password.
- [x] Add/Edit/Remove products from API.

**Comment by JMace88** [comment]
Admin is now a key in the user data. It has been applied to only the 4 project creators. Since our admin passwords are in the seed data we may want to find a security measure to secure this access.

**Comment by MikeyJaay** [comment]
All views are available, now need to add token functionality so only admin = true can view
