### ISSUE TITLE
Plant Photos for API

### ISSUE THREAD

**Issue by JMace88** [2401-Group-A/Capstone-EComSite#21]
Here is the list of starter plants for our API. We will need to have a picture for each one.
- [x] Cilantro
- [x] Basil
- [x] Mint
- [x] Oregano
- [x] Parsley
- [x] Spinach
- [x] Arugula
- [x] Lettuce
- [x] Cabbage
- [x] Pea
- [x] Radish
- [x] Tomato, Cherry
- [x] Tomato, Roma
- [x] Tomato, Beefsteak
- [x] Bell Pepper
- [x] Jalapeno Pepper
- [x] Habanero Pepper
- [x] Cucumber
- [x] Onion
- [x] Carrot
- [x] Zucchini
- [x] Green Bean

**Comment by MikeyJaay** [comment]
Done! Pushed to GitHub via Images branch
