### ISSUE TITLE
Admin Boolean in User Table

### ISSUE THREAD

**Issue by MikeyJaay** [2401-Group-A/Capstone-EComSite#80]
Example: admin BOOLEAN default 'False'

const users = [
  {
    firstname: 'Josh',
    lastname: 'Mace',
    email: 'joshuamace@gmail.com',
    password: 'josh123',
    address: 'Some Place',
    city: 'Dallas',
    state: 'Texas',
    zipcode: '75287',
    admin: 'TRUE',
  },

**Comment by JMace88** [comment]
Looks good. 👍
